modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="more_tools"
version="1.0.0"
displayName="more Tools"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Emad, MCreator"

[[dependencies.more_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



